### ISSUE TITLE
PassatGTE range status not showing

### ISSUE THREAD

**Issue by GrandTourette** [tillsteinbach/WeConnect-cli#10]
Login works well, but get status after query range is not showing:
"weconnect-cli --verbose --username foobar --password foobar get /vehicles/WVWDEADBEEF/status"

....working "well" ....
[rangeStatus]
        Error: Error 4003: The performed call is unauthorized info: Something went wrong. Please try to re-login. If the problem persists, please contact our support.
[parkingPosition] (last captured 2021-08-23T05:04:09+00:00)
... working well...

--verbose setting does not work......

**Comment by tillsteinbach** [comment]
@GrandTourette: Actually this is a problem within the WeConnect backend. Nothing I could do about. But it should fix itself.
