### ISSUE TITLE
Set the temperature

### ISSUE THREAD

**Issue by waxipedia** [tillsteinbach/WeConnect-cli#133]
Does anyone know how to set the temperature before starting the climatization?
/vehicles/{myvin}/controls/climatisation start
just starts the climatization.

**Comment by tillsteinbach** [comment]
You can give the desired temperature instead of „start“

**Comment by waxipedia** [comment]
Sometimes the solutition is so obvious. Thanks

**Comment by tillsteinbach** [comment]
Happy to help!
