### ISSUE TITLE
Does the WeConnect API support MBB platform vehicles ?

### ISSUE THREAD

**Issue by Jonkrist** [tillsteinbach/WeConnect-cli#134]
Hi,
I have two VW cars, one e-Golf and one ID.4
VW has lately abandoned the old We-Connect App and Renamed the We-Connect ID app to Volkswagen. This app now handles both cars. I thus wondered if your API could now also handle both car types.
This is interesting because it seems that the HomeAssistant custom integration also use your Python API.

I tried weconnect-cli, and it finds both cars.
However, when listing tags for the e-Golf, 'capabilities', 'domains' and 'controls' are missing.
I only get this:

  xx.xx@gmail.com@weconnect-sh:/vehicles/WVWZZZAU.....$ls tags
  ..
  vin
  role
  enrollmentStatus
  userRoleStatus
  model
  devicePlatform
  nickname
  brandCode
  images
  tags
  pictures

When using the "cat" command I only get this:

  Vehicle: WVWZZZ.........
  VIN:               WVWZZZ...........
  Model:             e-Golf
  Device Platform:   MBB
  Nickname:          e-GOLF COMFO 100 E1F
  Brand Code:        V
  Role:              PRIMARY_USER
  Enrollment Status: COMPLETED
  User Role Status:  ENABLED

Is this caused my missing support for MBB platforms in the library?
Or is there something in the the VW server implementation that causes this?

Thanks.
Jon

**Comment by tillsteinbach** [comment]
When both cars are usable with the new app it is likely that it should work. But it is a bit strange that it is not working right away

**Comment by Jonkrist** [comment]
Ok, thank you.
I also get some errors on the ID.4:

- Entity sensor.id_4_gtx_last_trip_average_electric_consumption (<class 'custom_components.volkswagen_we_connect_id.sensor.VolkswagenIDVehicleSensor'>) is using state class 'measurement' which is impossible considering device class ('energy') it is using; expected None or one of 'total_increasing', 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the author of the 'volkswagen_we_connect_id' custom integration
- /vehicles/WVWxx /domains/climatisationTimers/climatisationTimersStatus/timers/2/singleTimer: Unknown attribute targetDateTime with value 2023-02-18T09:00:00Z
- /vehicles/WVWxx : Unknown attribute climatisationTimersStatus with value {'value': {'carCapturedTimestamp': '2024-02-25T10:49:46Z', 'timeInCar': '2024-02-25T11:49:45+01:00', 'timers': [{'id': 1, 'enabled': True, 'recurringTimer': {'startTime': '06:45', 'recurringOn': {'mondays': True, 'tuesdays': True, 'wednesdays': True, 'thursdays': True, 'fridays': True, 'saturdays': False, 'sundays': False}, 'targetTime': '06:45', 'repetitionDays': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday']}}, {'id': 2, 'enabled': False, 'singleTimer': {'startDateTime': '2023-02-18T09:00:00Z', 'targetDateTime': '2023-02-18T09:00:00Z'}}]}} in domain departureTimers
- /vehicles/WVWxx : Unknown attribute temperatureOutsideStatus with value {'error': {'message': 'Bad Gateway', 'errorTimeStamp': '2024-02-25T17:02:08Z', 'info': 'Upstream service responded with an unexpected status. If the problem persists, please contact our support.', 'code': 4007, 'group': 2, 'retry': True}} in domain measurements
- /vehicles/WVWxx : Vehicle data for WVWxx is empty, this can happen when there are too many requests
- Trips could not be fetched for car WVWxx due to too many requests.

I presume the last few of those may be related to "too many requests", but not all of them.
I am an experienced programmer and know Python. I may be interested in contributing or doing some testing if I can fine some spare time :).
If you have any suggestions on where to start, that would be appreciated.
More specifically, there seems to be a lot of different urls used to authenticate and get data. Any info on this and how to log the raw output for analysis would be helpful.

Thanks again.
Jon

**Comment by tillsteinbach** [comment]
the first message is coming from another integration right? some of the warnings will go away after you update
