### ISSUE TITLE
Import Fehler

### ISSUE THREAD

**Issue by xerion3800** [tillsteinbach/WeConnect-cli#14]
Ich bekomme beim ausführen immer Import Fehler:

PS C:\Users\frank\Downloads\WeConnect-cli-main\WeConnect-cli-main> & C:/Users/frank/AppData/Local/Programs/Python/Python39/python.exe c:/Users/frank/Downloads/WeConnect-cli-main/WeConnect-cli-main/weconnect_cli/weconnect_cli.py --help
Traceback (most recent call last):
  File "c:\Users\frank\Downloads\WeConnect-cli-main\WeConnect-cli-main\weconnect_cli\weconnect_cli.py", line 17, in <module>
    from .__version import __version__
ImportError: attempted relative import with no known parent package
PS C:\Users\frank\Downloads\WeConnect-cli-main\WeConnect-cli-main>

**Comment by tillsteinbach** [comment]
Das sieht mir so aus also es von GitHub runtergeladen wurde, ich würde zum installieren lieber pip benutzen:
```
pip install weconnect-cli
weconnect-cli --version
weconnect-cli 0.14.7 (using WeConnect-python 0.20.6)
```
das gibt die letzte stabile Version.

Wenn es trotzdem der unreleaste teil von GitHub sein soll (latest and greatest ;) ) dann am besten im gecloneten folder:
```
pip install -e .
weconnect-cli --version
weconnect-cli develop (using WeConnect-python develop)
```

**Comment by xerion3800** [comment]
Danke ja das wars. Ich hatte es direkt geclont und wollte es starten.
