### ISSUE TITLE
Accepting terms and conditions

### ISSUE THREAD

**Issue by mschafr** [tillsteinbach/WeConnect-cli#24]
I get the following message when trying to read status data:
<code>CRITICAL:weconnect-cli:There was a problem when authenticating with WeConnect: You have to login at myvolkswagen.de and accept the terms and conditions</code>
Is it possible to catch this condition and accept the terms through the CLI as well?

**Comment by tillsteinbach** [comment]
No, as I cannot display the terms I don't want to be responsible that someone accepts something he has never seen.
I know that no one reads that, but I don't want to be blamed.
