### ISSUE TITLE
cannot "cd" to a node with numeric name

### ISSUE THREAD

**Issue by thgau** [tillsteinbach/WeConnect-cli#32]
Nice tool, but I have a small problem:
My ID.4 has numeric nodes in the climatisationTimer tree:

I can list the nodes with find:

user@domain@weconnect-sh:/vehicles/WVGZZZE2ZXXXXXXX/status/climatisationTimer/timers$find
/vehicles/WVGZZZE2ZXXXXXXX/status/climatisationTimer/timers
/vehicles/WVGZZZE2ZXXXXXXX/status/climatisationTimer/timers/1
/vehicles/WVGZZZE2ZXXXXXXX/status/climatisationTimer/timers/1/enabled
/vehicles/WVGZZZE2ZXXXXXXX/status/climatisationTimer/timers/1/singleTimer
/vehicles/WVGZZZE2ZXXXXXXX/status/climatisationTimer/timers/1/singleTimer/startDateTime
/vehicles/WVGZZZE2ZXXXXXXX/status/climatisationTimer/timers/2
/vehicles/WVGZZZE2ZXXXXXXX/status/climatisationTimer/timers/2/enabled
/vehicles/WVGZZZE2ZXXXXXXX/status/climatisationTimer/timers/2/singleTimer
/vehicles/WVGZZZE2ZXXXXXXX/status/climatisationTimer/timers/2/singleTimer/startDateTime

But I cannot "cd" into it:
user@domain@weconnect-sh:/vehicles/WVGZZZE2ZXXXXXXX/status/climatisationTimer/timers$cd 1
*** 1 does not exist
user@domain@weconnect-sh:/vehicles/WVGZZZE2ZXXXXXXX/status/climatisationTimer/timers$pwd
/vehicles/WVGZZZE2ZXXXXXXX/status/climatisationTimer/timers

reading the whole tree content with cat does work:
user@domain@weconnect-sh:/vehicles/WVGZZZE2ZXXXXXXX/status/climatisationTimer/timers$cat
[1: Enabled: False at 2021-11-14T07:25:00+00:00 , 2: Enabled: True at 2021-11-19T16:35:00+00:00 ]

**Comment by tillsteinbach** [comment]
Should be fixed in 0.16.1 release

**Comment by thgau** [comment]
unbelievable correction speed  :-) 
it works.
