### ISSUE TITLE
Climatisation does not start

### ISSUE THREAD

**Issue by mitch-dc** [tillsteinbach/WeConnect-cli#37]
Hi dev,

Thanks for all the work on the CLI!

I'm trying to start the climatisation from the command line for my ID.4, but it does not start and i dont get any feedback why not:
`weconnect-cli --username XXXXX --password XXXXXX set /vehicles/WVGZZZE2ZMXXXXX/controls/climatisation start`

I do get a message when i use the wrong command (not stop or start).

**Comment by tillsteinbach** [comment]
There can be plenty of reasons why it does not start. Try something like:
`weconnect-cli --username XXXXX --password XXXXXX --no-cache get /` and then have a look in the climatisation section. You should find your request and the result there. Possible status are:
```
            SUCCESSFULL = 'successful'
            FAIL = 'fail'
            POLLING_TIMEOUT = 'polling_timeout'
            IN_PROGRESS = 'in_progress'
            QUEUED = 'queued'
            DELAYED = 'delayed'
            TIMEOUT = 'timeout'
            FAIL_VEHICLE_IS_OFFLINE = 'fail_vehicle_is_offline'
            FAIL_IGNITION_ON = 'fail_ignition_on'
            FAIL_BATTERY_LOW = 'fail_battery_low'
            FAIL_PLUG_ERROR = 'fail_plug_error'
            UNKNOWN = 'unknown status'
```

hope that helps.

**Comment by mitch-dc** [comment]
Hmm with that command i don't get any feedback on previous calls:

`Vehicle: XX
VIN:               XX
Model:             ID.4
Device Platform:   WCAR
Nickname:          Komo
Role:              PRIMARY_USER
Enrollment Status: COMPLETED
User Role Status:  ENABLED
Capabilities: 35 items
        [automation] disabling: True (expires 2024-09-24T23:59:59+00:00)
        [batteryChargingCare] Status: MISSING_SERVICE disabling: False
        [batteryColdWarning] Status: MISSING_SERVICE disabling: False
        [batterySupport] Status: MISSING_SERVICE disabling: False
        [cdisDigitalKey] Status: MISSING_SERVICE disabling: False
        [charging] disabling: True (expires 2024-09-24T23:59:59+00:00)
        [chargingStations] disabling: True (expires 2024-09-24T23:59:59+00:00)
        [climatisation] disabling: True (expires 2024-09-24T23:59:59+00:00)
        [dealerAppointment] Status: MISSING_SERVICE disabling: False
        [destinations] disabling: True (expires 2024-09-24T23:59:59+00:00)
        [fuelStatus] disabling: False (expires 2024-09-24T23:59:59+00:00)
        [ignition] disabling: False (expires 2024-09-24T23:59:59+00:00)
        [mapUpdate] disabling: True (expires 2024-09-24T23:59:59+00:00)
        [measurements] Status: MISSING_SERVICE disabling: False
        [onlineSpeech] disabling: True (expires 2024-09-24T23:59:59+00:00)
        [parkingBrake] Status: MISSING_SERVICE disabling: False
        [parkingInformation] disabling: True (expires 2024-09-24T23:59:59+00:00)
        [parkingPosition] Status: MISSING_SERVICE disabling: False
        [personalizationOnline] Status: MISSING_SERVICE disabling: False
        [plugAndCharge] Status: MISSING_SERVICE disabling: False
        [poiSearch] Status: MISSING_SERVICE disabling: False
        [privateEmergencyCall] Status: MISSING_SERVICE disabling: False
        [readiness] disabling: False
        [roadExperienceManagementLocalization] Status: MISSING_SERVICE disabling: False
        [roadExperienceManagementLocalizationUpload] Status: MISSING_SERVICE disabling: False
        [roadsideAssistant] Status: MISSING_SERVICE disabling: False
        [routing] disabling: True (expires 2024-09-24T23:59:59+00:00)
        [state] Status: MISSING_SERVICE disabling: False
        [trafficInformation] disabling: True (expires 2024-09-24T23:59:59+00:00)
        [vehicleHealth] Status: MISSING_SERVICE disabling: False
        [vehicleHealthInspection] Status: MISSING_SERVICE disabling: False
        [vehicleHealthWarnings] Status: MISSING_SERVICE disabling: False
        [vehicleLights] Status: MISSING_SERVICE disabling: False
        [vehicleWakeUpTrigger] Status: MISSING_SERVICE disabling: False
        [webRadio] disabling: True (expires 2024-09-24T23:59:59+00:00)
Domains: 6 items
[automation] Elements: 2 items
        [climatisationTimer] (last captured 2022-01-10T14:47:47+00:00)
                Time in Car: 2022-01-10T15:47:47+01:00 (captured at 2022-01-10T14:47:47+00:00)
                Timers: 2 items
                        1: Enabled: True at 06:30 on mondays tuesdays wednesdays thursdays fridays saturdays sundays
                        2: Enabled: True at 07:00 on mondays tuesdays wednesdays thursdays fridays saturdays sundays
        [chargingProfiles]
                Error:  Error 4103: Resource could not be found
                        info: Internal error, please try again later. If the problem persists, please contact our support.
                        timestamp: 2022-01-10 15:06:28+00:00
                Profiles: 0 items
[userCapabilities] Elements: 1 items
        [capabilitiesStatus]
                Capabilities: 35 items
                        [automation] disabling: True (expires 2024-09-24T23:59:59+00:00)
                        [batteryChargingCare] Status: MISSING_SERVICE disabling: False
                        [batteryColdWarning] Status: MISSING_SERVICE disabling: False
                        [batterySupport] Status: MISSING_SERVICE disabling: False
                        [cdisDigitalKey] Status: MISSING_SERVICE disabling: False
                        [charging] disabling: True (expires 2024-09-24T23:59:59+00:00)
                        [chargingStations] disabling: True (expires 2024-09-24T23:59:59+00:00)
                        [climatisation] disabling: True (expires 2024-09-24T23:59:59+00:00)
                        [dealerAppointment] Status: MISSING_SERVICE disabling: False
                        [destinations] disabling: True (expires 2024-09-24T23:59:59+00:00)
                        [fuelStatus] disabling: False (expires 2024-09-24T23:59:59+00:00)
                        [ignition] disabling: False (expires 2024-09-24T23:59:59+00:00)
                        [mapUpdate] disabling: True (expires 2024-09-24T23:59:59+00:00)
                        [measurements] Status: MISSING_SERVICE disabling: False
                        [onlineSpeech] disabling: True (expires 2024-09-24T23:59:59+00:00)
                        [parkingBrake] Status: MISSING_SERVICE disabling: False
                        [parkingInformation] disabling: True (expires 2024-09-24T23:59:59+00:00)
                        [parkingPosition] Status: MISSING_SERVICE disabling: False
                        [personalizationOnline] Status: MISSING_SERVICE disabling: False
                        [plugAndCharge] Status: MISSING_SERVICE disabling: False
                        [poiSearch] Status: MISSING_SERVICE disabling: False
                        [privateEmergencyCall] Status: MISSING_SERVICE disabling: False
                        [readiness] disabling: False
                        [roadExperienceManagementLocalization] Status: MISSING_SERVICE disabling: False
                        [roadExperienceManagementLocalizationUpload] Status: MISSING_SERVICE disabling: False
                        [roadsideAssistant] Status: MISSING_SERVICE disabling: False
                        [routing] disabling: True (expires 2024-09-24T23:59:59+00:00)
                        [state] Status: MISSING_SERVICE disabling: False
                        [trafficInformation] disabling: True (expires 2024-09-24T23:59:59+00:00)
                        [vehicleHealth] Status: MISSING_SERVICE disabling: False
                        [vehicleHealthInspection] Status: MISSING_SERVICE disabling: False
                        [vehicleHealthWarnings] Status: MISSING_SERVICE disabling: False
                        [vehicleLights] Status: MISSING_SERVICE disabling: False
                        [vehicleWakeUpTrigger] Status: MISSING_SERVICE disabling: False
                        [webRadio] disabling: True (expires 2024-09-24T23:59:59+00:00)
[charging] Elements: 5 items
        [batteryStatus] (last captured 2022-01-10T14:47:51+00:00)
                Current SoC: 67%
                Range: 160km
        [chargingStatus] (last captured 2022-01-10T14:47:51+00:00)
                State: readyForCharging
                Mode: manual
                Remaining Charging Time: 0 minutes
                Charge Power: 0 kW
                Charge Rate: 0 km/h
        [chargingSettings] (last captured 2022-01-10T14:47:51+00:00)
                Request: settings operation, status in_progress
                Maximum Charge Current AC: reduced
                Auto Unlock When Charged: off
                Target SoC: 100 %
        [chargeMode]
                Preferred charge mode: manual
                Available charge modes: [invalid]
        [plugStatus] (last captured 2022-01-10T14:47:50+00:00)
                Plug: disconnected, unlocked
[climatisation] Elements: 3 items
        [climatisationStatus] (last captured 2022-01-10T14:49:23+00:00)
                State: off
                Remaining Climatization Time: 0 min
        [climatisationSettings] (last captured 2022-01-10T14:47:50+00:00)
                Target Temperature in °C: 21.0 °C
                Target Temperature in °F: 70.0 °F
                Temperature unit in car: celsius
                Climatization without external Power: True
                Start climatization after unlock: True
                Window heating: True
                Heating Front Left Seat: True
                Heating Front Right Seat: False
        [windowHeatingStatus] (last captured 2022-01-10T14:49:23+00:00)
                Windows: 2 items
                        front: off
                        rear: off
[fuelStatus] Elements: 1 items
        [rangeStatus] (last captured 2022-01-10T14:47:51+00:00)
                Car Type: electric
                Total Range: 160 km
                Primary Engine: electric  SoC: 67% (160 km)
[readiness] Elements: 1 items
        [readinessStatus]
                Connection State:
                        Is online: True
                        Is active: False
                        Battery power level: comfort
                        Daily Power Budget Available: True
                Connection Warning:
                        Insufficient Battery Level Warning: False
                        Daily Power Budget Warning: False`

**Comment by mitch-dc** [comment]
It resolved itself, i can not stop and start the climatization. 

`PS C:\WINDOWS\system32> weconnect-cli --username XXX@gmail.com --password XXX set /vehicles/XXX/controls/climatisation stop
PS C:\WINDOWS\system32> weconnect-cli --username XXX@gmail.com --password XXX set /vehicles/XXX/controls/climatisation start`
