### ISSUE TITLE
only 3 changes possible

### ISSUE THREAD

**Issue by tasisale** [tillsteinbach/WeConnect-cli#39]
what i have tested, it is only possilbe to make 3 changes via CLI or MQTT, then the VW-Servers says: -> 
ignition must be switched on to protect the battery

i think that is new, again 1 week or so.
can you confirm it?

regards
simon

**Comment by tillsteinbach** [comment]
Is it possible that you are making something wrong in your MQTT client? It looks like you are not sending one command but a big number of requests.

**Comment by tasisale** [comment]
i don' think so, but the message will be show in the app.
here a picture after set maxlaodAC.
![Foto 22-01-24 11-15-10 5621](https://user-images.githubusercontent.com/78930595/150764601-8b3ced77-4e33-4f5f-9741-6c4b02eaa24c.png)
![Foto 22-01-24 11-16-08 5622](https://user-images.githubusercontent.com/78930595/150764605-a8ce4094-5633-4aa2-b08e-96c80acee772.png)

**Comment by tillsteinbach** [comment]
Hmmm, I have to check that. The silly thing about MQTT is that messages on topics you are publishing and subscribing to are doing circles. So maybe I will change that behaviour completely to have separate topics for reading/writing

**Comment by tasisale** [comment]
ok, thx.
when i can do anything to test or change, write me.

regards
simon

**Comment by tasisale** [comment]
if the problem given, the cli output are:

`weconnect-cli --username xxxxxxx --password xxxxxxx set /vehicles/WVWZZZAUZLW916270/controls/climatisation start
id /vehicles/WVWZZZAUZLW916270/controls/climatisation cannot be set: Could not control climatisation (The maximum amount of requests has been reached - Because of battery protection... (you can still lock your car). - No retry possible)`

**Comment by tasisale** [comment]
hi have you any news tested?

regards
simon

**Comment by tillsteinbach** [comment]
Did you try the new release?

**Comment by tasisale** [comment]
yes

**Comment by tasisale** [comment]
will test now again and write here.

**Comment by tasisale** [comment]
ok have make 20 chnages, with no new block.
thats work now perfect. thx
