### ISSUE TITLE
no function to set maxChargeCurrentAC

### ISSUE THREAD

**Issue by tasisale** [tillsteinbach/WeConnect-cli#40]
`weconnect-cli --username xxxxxxxxx --password xxxxxxxxx set /vehicles/WVWZZZAUZLW916270/domains/charging/chargingSettings/maxChargeCurrentAC maximum
id /vehicles/WVWZZZAUZLW916270/domains/charging/chargingSettings/maxChargeCurrentAC cannot be set: Could not set value (Resource could not be found - Internal error, please try again later. If the problem persists, please contact our support. - Please retry in a moment)
`

via WeConnect App i can set the maxChargeCurrentAC to 5/10/13 and MAX without problems.

**Comment by tasisale** [comment]
the same error by set climatisationWithoutExternalPower

`weconnect-cli --username xxxxxxxxx --password xxxxxxxxx set /vehicles/WVWZZZAUZLW916270/domains/climatisation/climatisationSettings/climatisationWithoutExternalPower False
id /vehicles/WVWZZZAUZLW916270/domains/climatisation/climatisationSettings/climatisationWithoutExternalPower cannot be set: Could not set value (The provided request is incorrect - Internal error, please try again later. If the problem persists, please contact our support. - Please retry in a moment)
`

**Comment by tillsteinbach** [comment]
That is an answer from the VW Servers I cannot do anything about.

**Comment by tasisale** [comment]
> That is an answer from the VW Servers I cannot do anything about.

ok, thx for the fast feedback
