### ISSUE TITLE
no right feedback by maxChargeCurrentAC value

### ISSUE THREAD

**Issue by tasisale** [tillsteinbach/WeConnect-cli#41]
i have test the in/output from maxChargeCurrentAC via CLI.
is set in App 5A the variable give me = reduced - back
is set in App to 10A or 13A it gives = invalid - back
is set via App to 16A it gives = maximum - back

there an Error or givs VW no more feedback to load?

regards
simon

**Comment by tillsteinbach** [comment]
The new API only knows maximum and reduced you can check in the WeConnect **ID** App

**Comment by tasisale** [comment]
yes, in the "ID"-APP i see only "maximum and reduced"

thx for your work
