### ISSUE TITLE
is it possilbe to set climatisation with an temperatur as parameter

### ISSUE THREAD

**Issue by tasisale** [tillsteinbach/WeConnect-cli#42]
i have the problem, i get no targetTemperature_C from VW Server.
so i start the climatisation via CLI and it starts, about with 20,5 °C.
is it possible to send the target Temperatur as parameter, or can i change it in the sorce of yout files to my value i want.

regards
simon

**Comment by tillsteinbach** [comment]
I‘m currently thinking of adding something like —backup-climate-temperature

**Comment by tillsteinbach** [comment]
After thinking about the problem I came up with a better solution that is already implemented and currently in testing:
Apart from "start" and "stop" you can start the climatisation now also with a temperature like "19.0"

**Comment by tasisale** [comment]
> After thinking about the problem I came up with a better solution that is already implemented and currently in testing: Apart from "start" and "stop" you can start the climatisation now also with a temperature like "19.0"

ok, fine.
how i can test it too?

regards
simon

**Comment by tillsteinbach** [comment]
You can install it with: `pip3 install weconnect-cli==0.25.0.dev1`

**Comment by tillsteinbach** [comment]
By now 0.25 is released. Closing this one
