### ISSUE TITLE
Error message: No credentials form found

### ISSUE THREAD

**Issue by Veelu** [tillsteinbach/WeConnect-cli#43]
Command:
weconnect-cli --username email@example.com --password VerySecret

Gives error message:
2022-01-28T13:18:24+0200:CRITICAL:There was a problem when communicating with WeConnect. If this problem persists please open a bug report: No credentials form found

Tested version:
weconnect-cli --version
weconnect-cli 0.23.1 (using WeConnect-python 0.35.0)

**Comment by tillsteinbach** [comment]
VW changed the login form. Will release an update as soon as possible!

**Comment by Veelu** [comment]
Ok. Keep up the good work!

**Comment by tillsteinbach** [comment]
Should be fixed with 0.23.2 will work on the details the next days, there was no time for testing. But I think it should be robust enough for now

**Comment by Veelu** [comment]
Done a quick test and looks that this works!
