### ISSUE TITLE
is it possilbe to implement, open and close with the s-pin

### ISSUE THREAD

**Issue by tasisale** [tillsteinbach/WeConnect-cli#45]
hi,

is it possilbe to implement, open and close the car with the s-pin.

regards
simon

**Comment by tillsteinbach** [comment]
No, currently there is no known endpoint for
that in the new API.

**Comment by tasisale** [comment]
> No, currently there is no known endpoint for that in the new API.

okay, thats a pity.
hopefully this will come back!

regards
simon

**Comment by tillsteinbach** [comment]
Will be considered once feature is available through API
