### ISSUE TITLE
Output format JSON

### ISSUE THREAD

**Issue by markussc** [tillsteinbach/WeConnect-cli#46]
Hi Till
Thanks for the great tool! Would it be possible to add an option to retrieve the output in JSON format? Especially for status information this would be really great.
BR
Markus

**Comment by tillsteinbach** [comment]
I was already thinking of this. Would you prefer the raw json as coming from the VW servers (with the risk that the structure changes more often) or would you prefer the (a bit more stable) output of the CLI but in json format?

**Comment by markussc** [comment]
As stable as possible would be nice! I'm especially interested in the batteryStatus and readinessStatus data.

**Comment by tillsteinbach** [comment]
Will put it on the Todo list without a particular promise when it will be available, but as it should be limited effort I think it can be ready in reasonable time.

**Comment by tillsteinbach** [comment]
Update: Does already work on my test branch. Will come in two flavours: `--format json` added to get command will switch the output to json. save command will also write a json file if the file ending is `.json`.

**Comment by tillsteinbach** [comment]
Now available in 0.24.0 release
