### ISSUE TITLE
Problems with CLI after install

### ISSUE THREAD

**Issue by roppenheimer** [tillsteinbach/WeConnect-cli#47]
I have installed the WeConnect-cli package using the command 

pip3 install weconnect-cli

The installation appeared to be successful but when I issue the command I get:
pi@raspberrypi:~ $ weconnect-cli
bash: weconnect-cli: command not found

Am I missing something?

**Comment by tillsteinbach** [comment]
what does `python --version` say?

**Comment by roppenheimer** [comment]
pi@raspberrypi:~ $ python --version
Python 2.7.16

Looks like I need to change the default version of Python?

**Comment by tillsteinbach** [comment]
exactly! You installed for python3 and your default version is python2

**Comment by roppenheimer** [comment]
pi@raspberrypi:~ $ python --version
Python 3.7.3
pi@raspberrypi:~ $ weconnect-cli
bash: weconnect-cli: command not found

**Comment by roppenheimer** [comment]
pi@raspberrypi:~ $ python -m pip install weconnect-cli
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: weconnect-cli in ./.local/lib/python3.7/site-packages (0.24.0)
Requirement already satisfied: ascii-magic~=1.6 in ./.local/lib/python3.7/site-packages (from weconnect-cli) (1.6)
Requirement already satisfied: weconnect[images]~=0.36.0 in ./.local/lib/python3.7/site-packages (from weconnect-cli) (0.36.0)
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from ascii-magic~=1.6->weconnect-cli) (0.3.7)
Requirement already satisfied: Pillow in ./.local/lib/python3.7/site-packages (from ascii-magic~=1.6->weconnect-cli) (9.0.1)
Requirement already satisfied: oauthlib~=3.1.1 in ./.local/lib/python3.7/site-packages (from weconnect[images]~=0.36.0->weconnect-cli) (3.1.1)
Requirement already satisfied: requests~=2.27.1 in ./.local/lib/python3.7/site-packages (from weconnect[images]~=0.36.0->weconnect-cli) (2.27.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests~=2.27.1->weconnect[images]~=0.36.0->weconnect-cli) (1.24.1)
Requirement already satisfied: idna<4,>=2.5; python_version >= "3" in /usr/lib/python3/dist-packages (from requests~=2.27.1->weconnect[images]~=0.36.0->weconnect-cli) (2.6)
Requirement already satisfied: charset-normalizer~=2.0.0; python_version >= "3" in ./.local/lib/python3.7/site-packages (from requests~=2.27.1->weconnect[images]~=0.36.0->weconnect-cli) (2.0.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests~=2.27.1->weconnect[images]~=0.36.0->weconnect-cli) (2018.8.24)
pi@raspberrypi:~ $ weconnect-cli
bash: weconnect-cli: command not found
pi@raspberrypi:~ $ python --version
Python 3.7.3

This is a default RPi installation so there are several versions of Python

**Comment by tillsteinbach** [comment]
hmmm, this is confusing me. I have to think what else could be going wrong here, sorry!

**Comment by tillsteinbach** [comment]
You could also try `python -m weconnect_cli` for now

**Comment by roppenheimer** [comment]
Sorted, I needed:

sudo pip3 install weconnect-cli

**Comment by tillsteinbach** [comment]
sometimes you just need root rights ;)

**Comment by roppenheimer** [comment]
Thanks for your help

**Comment by roppenheimer** [comment]
When I try to use a .netrc file I get the error:

  File "/usr/local/bin/weconnect-cli", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/weconnect_cli/weconnect_cli_base.py", line 152, in main
    secrets = netrc.netrc(file=args.netrc)
  File "/usr/lib/python3.7/netrc.py", line 30, in __init__
    self._parse(file, fp, default_netrc)
  File "/usr/lib/python3.7/netrc.py", line 107, in _parse
    " the owner", file, lexer.lineno)
netrc.NetrcParseError: ~/.netrc access too permissive: access permissions must restrict access to only the owner

**Comment by tillsteinbach** [comment]
Yes, the permissions must be more restricted:
`chmod og-rw .netrc`
you don't want anyone else than yourself to be able to read the passwords

**Comment by roppenheimer** [comment]
Thanks Till, I got that sorted and have managed to exchange some MQTT messages with the car.

 

I’m struggling to work out how to request a particular parameter – as far as I can see I need to publish a topic along the lines of:

 

weconnect/0/vehicles/[My VIN]/charging/chargingSettings/request/0/status

weconnect/0/vehicles/[My VIN]/domains/charging/chargingSettings/request/0/operation

weconnect/0/vehicles/[My VIN]/domains/charging/chargingSettings/request/0/body

weconnect/0/vehicles/[My VIN]/domains/charging/chargingSettings/request/0/requestId

weconnect/0/vehicles/[My VIN]/domains/charging/chargingSettings/request/0/vcfRequestId

 

 

Is that right?

 

Thanks

**Comment by tillsteinbach** [comment]
If you just want to read data from the car you just have to subscribe to that topic. You get the data published every time it changes. If you want to know which topics are available you can subscribe to `weconnect/0/mqtt/topics` or add the `--list-topics` parameter when starting.
You only have to publish something to a topic when you want to change a setting or control e.g. the climatization.

**Comment by roppenheimer** [comment]
OK, thanks. Is there  a way to retrieve the current value of a parameter without waiting for it to change?

**Comment by tillsteinbach** [comment]
Usually your broker will store the value and send it to you on subscribe.

**Comment by tillsteinbach** [comment]
What you can also do is add Parameter `--republish-on-update` but that causes all values to be sent after each update. So in my opinion it is the less preferred way.

**Comment by roppenheimer** [comment]
Thanks for your help
