### ISSUE TITLE
Crash after logging in

### ISSUE THREAD

**Issue by mtbsteve** [tillsteinbach/WeConnect-cli#5]
I just installed the WeConnect CLI and get the following error when I try to logon with:
weconnect-cli --username xxxx --password yyyyy
I am running Ubuntu 18.04 and have python 3.6.9 installed.
```
file "/home/stephan/.local/lib/python3.6/site-packages/weconnect/util.py", line 11, in robustTimeParse
    return datetime.fromisoformat(timestring)
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
```

**Comment by tillsteinbach** [comment]
Hi, the problem is that python 3.6 is not supported. You would need to update to at least python 3.7
