### ISSUE TITLE
Possibility to get service information

### ISSUE THREAD

**Issue by Sh0n** [tillsteinbach/WeConnect-cli#54]
Hi, 

In we connect app for Golf GTE (not we connect ID), we can get the "service" information. 
Any way to have this information on your plugin ?

Thanks in advance !

**Comment by tillsteinbach** [comment]
You mean the days and kilometers until service?

If your car provides it, it should be already there:
```
[vehicleHealthInspection] Elements: 1 items
	[maintenanceStatus] (last captured 2022-03-01T07:26:33+00:00)
		Current milage: 10504 km
		Inspection due in: -436 days
		Inspection due in: -19600 km
		Oil service in: -4600 km
		Oil service in: -71 days
[vehicleHealthWarnings] Elements: 1 items
	[warningLights] (last captured 2022-03-01T07:26:33+00:00)
		Current milage: 10504 km
		Warning Lights: []
```

What you need is: `[vehicleHealthInspection]` in the capabilities. If it says: `[vehicleHealthInspection] Status: MISSING_SERVICE disabling: False` your WeConnect Plus may be expired.

**Comment by tillsteinbach** [comment]
any update on this one?

**Comment by Sh0n** [comment]
Hi @tillsteinbach !

Sorry for the delay :(
When i check my WeConnect app on iPhone, I can read inspection (in days and km). 

But with this plugin, when I try /vehicleHealthInspection/maintenanceStatus/inspectionDue_days or /vehicleHealthInspection/maintenanceStatus/inspectionDue_km, I have "not found" response.

Any idea why ?

Thanks in advance !

**Comment by tillsteinbach** [comment]
Can you check in the WeConnect ID app if it has the maintenance data?

**Comment by Sh0n** [comment]
In WeConnect ID app, I can't find the maintenance date :( I think is the response right ?

**Comment by tillsteinbach** [comment]
It looks like this:

![7B2EB865-6E80-43BC-90C0-33B89E4845D3](https://user-images.githubusercontent.com/3825852/179285950-57262d8a-a9ec-4c32-9da1-c6cc23e9bb13.jpeg) 

![866A89BA-8E7B-4FBF-BF2B-4FC3C57933EB](https://user-images.githubusercontent.com/3825852/179285947-c100dc87-9ded-4f3d-bf15-3dde869eec8b.jpeg)
