### ISSUE TITLE
Form does not contain postAction

### ISSUE THREAD

**Issue by stefanjay** [tillsteinbach/WeConnect-cli#57]
When trying to login using

`weconnect-cli --username user@mail.com --password "s3cret" list`

it returns: `2022-03-21T22:06:36+0100:CRITICAL:There was a problem when communicating with WeConnect. If this problem persists please open a bug report: Form does not contain postAction`

**Comment by tillsteinbach** [comment]
my guess is that you have a typo in your username. I have to check if I can improve the error message
