### ISSUE TITLE
Temporarily no response from command line

### ISSUE THREAD

**Issue by gerhard1951** [tillsteinbach/WeConnect-cli#72]
I really appreciate your work. Unfortunately there is strange problem with WeConnect-cli: It works fine from morning to afternoon and informs about battery status, range, odometer, door status and lock status as expected, every 5 minutes.
In the afternoon of the day, only battery status and range is reported correctly, all other commands do not give back the expected value, but (for odometer for instance)  "id /vehicles/WVWXXXXXXXXXX/domains/measurements/odometerStatus/odometer not found".
This continues until the next morning, then the correct value ist shown again (till afternoon)
What could be the reason for this strange behaviour?
Thanks for your reply
Gerhard

**Comment by gerhard1951** [comment]
Hi Till,

 

my car is an ID.3, model 2022. I get always (all the day long) correct values for “…charging/batteryStatus/currentSOC_pct”and “… charging/batteryStatus/cruisingRangeElectric_km”, but for “…/measurements/odometerStatus/odometer”  and others correct values in the morning, but no response from afternoon on. The command line is always the same.

 

 

 

Von: Till Steinbach ***@***.***> 
Gesendet: Donnerstag, 7. Juli 2022 17:30
An: tillsteinbach/WeConnect-cli ***@***.***>
Cc: gerhard1951 ***@***.***>; Author ***@***.***>
Betreff: Re: [tillsteinbach/WeConnect-cli] Temporarily no response from command line (Issue #72)

 

Hello Gerhard, what kind of car is it, and do you get correct values in the App at the same time?

**Comment by tillsteinbach** [comment]
Hmmm, you are one of the lucky ones that already have a car with 3.0 software. Unfortunately I have some more weeks to wait for my update. So it is hard for me to tell what might be the problem and if it is common.
My stomach feeling is that it is a problem on VW side but I‘m of course not sure.
Is the data coming back when you drive the car?
I‘m afraid that we need to wait for some other user to check if it is a common problem.

**Comment by gerhard1951** [comment]
After driving a few kilometers nothing changed – unfortunately. Let´s wait if this is a common problem. To get the problem solved is nice to me, but not of highest importance, because the relevant parameters for me – battery status and range – do always work,

 

 

Von: Till Steinbach ***@***.***> 
Gesendet: Donnerstag, 7. Juli 2022 17:55
An: tillsteinbach/WeConnect-cli ***@***.***>
Cc: gerhard1951 ***@***.***>; Author ***@***.***>
Betreff: Re: [tillsteinbach/WeConnect-cli] Temporarily no response from command line (Issue #72)

 

Hmmm, you are one of the lucky ones that already have a car with 3.0 software. Unfortunately I have some more weeks to wait for my update. So it is hard for me to tell what might be the problem and if it is common.
My stomach feeling is that it is a problem on VW side but I‘m of course not sure.
Is the data coming back when you drive the car?
I‘m afraid that we need to wait for some other user to check if it is a common problem.

**Comment by gerhard1951** [comment]
Mwanwhile I found out, that
- every night from exactly 02.07 am on all requests including odometer and door-status work until sometime in the afternoon between 2.00 and 5.00 pm. 
- Using an ioBroker-adapter for requesting the above mentioned parameters, I get the same result: No door status or odometer value from afternoon on.
- It seems to be a Volkswagen problem.
- Is there a chance to contact Volkswagen concerning such a problem?

**Comment by tillsteinbach** [comment]
Thank you for the update.
Regarding contacting the Volkswagen support: I don’t believe that Volkswagen is interested in helping making third party software that uses their API work, but if you experience the same behavior on the official WeConnect ID app (it should behave the same) then of course you can report it there. If they fix it for the official app it will be fixed for WeConnect-cli too.

**Comment by gerhard1951** [comment]
Unfortunately, last year my ID.3 had to spend nearly four months in the garage because of software and hardware problems. Therefore I could not follow up the above mentioned problem. Meanwhile it seems to be solved.
