### ISSUE TITLE
CLI returns "None" for every request

### ISSUE THREAD

**Issue by markussc** [tillsteinbach/WeConnect-cli#78]
Whenever using the CLI interface, the response (including JSON responses) contains the string "None" at the very beginning. This leads to non interpretable JSON format.

Reproduce like this: 
$ weconnect-cli --username=<myusername> --password=<mypassword>

Leads to:
None
Welcome! Type ? to list commands

**Comment by tillsteinbach** [comment]
Shame on me, that is left over debug output. Will release a fix asap

**Comment by tillsteinbach** [comment]
Can you check that this is fixed in 0.32.1?

**Comment by markussc** [comment]
Thanks @tillsteinbach , this fixes the issue.
