### ISSUE TITLE
Window heating not starting (4104 Bad Gateway)

### ISSUE THREAD

**Issue by jlgarbayo** [tillsteinbach/WeConnect-cli#80]
Thank you for this package, it's really awesome. I got it up and running in a few minutes.
I can start and stop climatisation without issues. However, when I try the window heating I get the following error:
`# weconnect-cli set /vehicles/XXX/controls/windowheating start`
`id /vehicles/XXX/controls/windowheating cannot be set: Could not control windowheating (Bad Gateway - Looks like your service has expired. Please update your service subscription. - No retry possible)`
The window heating function is working smoothly in the app. The car is a Passat GTE 2021.

If I run:
`#weconnect-cli get /`
then I see the same error in several places, all related to battery and charging:
```
[chargingProfiles] Elements: 1 items
        [chargingProfilesStatus]
                Error:  Error 4104: Bad Gateway
                        info: Looks like your service has expired. Please update your service subscription.
                        timestamp: 2022-09-07 13:43:13+00:00
                        Profiles: 0 items

```
Thanks for your help!

**Comment by tillsteinbach** [comment]
Hey! Unfortunately not all features are available for all cars. Window heating also does not work for my Passat GTE. It does for the ID.3
Maybe this will change in the future.

**Comment by jlgarbayo** [comment]
Hi Till,
Understood! Thanks a lot for the quick response.

**Comment by jlgarbayo** [comment]
Hi Till,
I just checked and the command /vehicles/XXX/controls/windowheating [start|stop] is now working! I'm curious, don't know if you corrected it or if VW changed something on their end. Anyway, good news! Thanks for your great work.

**Comment by tillsteinbach** [comment]
Oh, that is good to know! Thanks for updating me!

**Comment by jlgarbayo** [comment]
It's my pleasure!
