### ISSUE TITLE
No credentials form found

### ISSUE THREAD

**Issue by thk4711** [tillsteinbach/WeConnect-cli#87]
when I start the script on a raspberry pi I get the following error:
`CRITICAL:weconnect-cli:There was a problem when communicating with WeConnect. If this problem persists please open a bug report: No credentials form found`
The same comman line on a MAC is working.

**Comment by tillsteinbach** [comment]
Can you check that you installed the latest version?

**Comment by thk4711** [comment]
I istalled it today. Just to be sure I also did pip3 install weconnect-cli --upgrade
` weconnect-cli --version
weconnect-cli 0.3.0`

**Comment by tillsteinbach** [comment]
That is super old. I guess your python is too old.

**Comment by thk4711** [comment]
You are right I went from python 3.6 to python 3.9 now it is working.
Thank You
