### ISSUE TITLE
Seems to be not working since 2 or 3 days...

### ISSUE THREAD

**Issue by PhilippeRigaux** [tillsteinbach/WeConnect-cli#90]
I get this error when trying to connect, no problem with Trinity or the wechargeid app
weconnect-cli --username xxxxxx --password xxxxx list
CRITICAL:weconnect-cli:There was a problem when communicating with WeConnect. If this problem persists please open a bug report: No credentials form found

Best

Philippe

**Comment by tillsteinbach** [comment]
What is the version you are running?

**Comment by PhilippeRigaux** [comment]
OK, I found the solution in one of the closed issues...

pip3.9 install weconnect-cli --upgrade

I installed my version with pip and on my system by default it is python 3.6...

Thx

Philippe

**Comment by tillsteinbach** [comment]
yes, unfortunately pip3.6 installs an old version that is not compatible with the servers anymore

**Comment by PhilippeRigaux** [comment]
Thx a lot, you can close the issue..

By the way your tool is really great I will use it in my domotic ( jeedom ) installation.

Have a nice day

Philippe

**Comment by tillsteinbach** [comment]
I have not heard of jeedom before, but just had a look. You might want to have a look at https://github.com/tillsteinbach/WeConnect-mqtt it looks like jeedom has a native possibility to connect with MQTT. This might save you some time.
