### ISSUE TITLE
All car capabilities lost today

### ISSUE THREAD

**Issue by 0rsa** [tillsteinbach/WeConnect-cli#91]
Hello,
Since this morning, after having to reconnect my car to my main profile, a lot of features are not available anymore.
I can get only static information like the vehicle model or the vehicle vin but all the informations I was getting from /vehicles/VIN/domains/[...] are not found, for example:

`id /vehicles/VIN/domains/charging/batteryStatus/currentSOC_pct not found`

I tried weconnect-mqtt and I can see that I'm missing some useful topics for my vehicle.

Are you experimenting the same thing from your side?

**Comment by tillsteinbach** [comment]
On my side everything is fine. What does the official WeConnect ID App say?

**Comment by 0rsa** [comment]
The official WeConnect app is working well with all the informations synced
I cleaned the cache, without success

**Comment by 0rsa** [comment]
The list of topics I get from mqtt:
![image](https://user-images.githubusercontent.com/769750/204078669-d184d0f9-022d-49f4-a2f9-0314e7aa9989.png)

Do we agree that I'm missing some useful topics?

**Comment by 0rsa** [comment]
Ok, using the We Connect official Web Portal, I have also an error

![image](https://user-images.githubusercontent.com/769750/204078907-c996313c-e9d8-4a0a-a564-89c3add63739.png)

I guess the issue is from VW, not from your nice library. I will just wait.

Thank you for your support!

**Comment by 0rsa** [comment]
Finally fixed on monday morning by VW Team. Services are up and running.
Don't expect something during a week-end (:
