### ISSUE TITLE
Error message: No credentials form found

### ISSUE THREAD

**Issue by WalterOH** [tillsteinbach/WeConnect-cli#95]
Command:
weconnect-cli --username [email@gmail.com](mailto:email@gmail.com) --password VerySecret

Give error message:
2023-01-05:CRITICAL:weconnect-cli:There was a problem when communicating with WeConnect. If this problem persists please open a bug report: No credentials form found

The email is a  @t-online.de (--> is the "-" a problem?) and the password includes a "!" and a "?" (--> seems to be no problem, a change led to the same error message). 

Running Python 3.6.3; car is ID3, access both for IOS and Android weconnect Apps run fine.

**Comment by tillsteinbach** [comment]
Python 3.6 is your problem. When you do a `weconnect-cli —version` you see that you got an outdated version that is not compatible with the VW Servers anymore.

**Comment by WalterOH** [comment]
Thank Till, your are right, now with python 3.10.8 all runs fine :-) 
My issue can be closed.

**Comment by tillsteinbach** [comment]
Perfect, happy to hear that!
